-- Inserindo 9 usuarios
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('lopreti@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('felintro@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('paiva@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('nofre@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('dorta@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('henrique@email.com', '123456');

INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('josedesouza@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('antoniosantos@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('joaosilva@email.com', '123456');

-- Inserindo 9 enderecos
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP, USUARIO_ID) VALUES ('Rua Teste 1', '01', 'São Paulo', 'Bairro Teste 1', '12345678', 1);
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP, USUARIO_ID) VALUES ('Rua Teste 2', '02', 'Pindamonhangaba', 'Bairro Teste 2', '12345678', 2);
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP, USUARIO_ID) VALUES ('Rua Teste 3', '03', 'Campinas', 'Bairro Teste 3', '12345678', 3);
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP, USUARIO_ID) VALUES ('Rua Teste 4', '04', 'Rio Claro', 'Bairro Teste 4', '12345678', 4);
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP, USUARIO_ID) VALUES ('Rua Teste 5', '05', 'Gramado', 'Bairro Teste 5', '12345678', 5);
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP, USUARIO_ID) VALUES ('Rua Teste 6', '06', 'Jundíai', 'Bairro Teste 6', '12345678', 6);

INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP, USUARIO_ID) VALUES ('Rua Teste 6', '06', 'Jundíai', 'Bairro Teste 6', '12345678', 7);
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP, USUARIO_ID) VALUES ('Rua Teste 6', '06', 'Jundíai', 'Bairro Teste 6', '12345678', 8);
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP, USUARIO_ID) VALUES ('Rua Teste 6', '06', 'Jundíai', 'Bairro Teste 6', '12345678', 9);

-- Inserindo 3 cursos
INSERT INTO CURSO (NOME_CURSO, TURNO) VALUES ('Administracao', 'MANHA');
INSERT INTO CURSO (NOME_CURSO, TURNO) VALUES ('Gestao', 'TARDE');
INSERT INTO CURSO (NOME_CURSO, TURNO) VALUES ('Tecnologia da Informacao', 'NOITE');

-- Inserindo 3 disciplinas
INSERT INTO DISCIPLINA (NOME) VALUES ('Contabilidade');
INSERT INTO DISCIPLINA (NOME) VALUES ('Lideranca');
INSERT INTO DISCIPLINA (NOME) VALUES ('Estrutura de Dados');

-- Inserindo 6 alunos
INSERT INTO ALUNO (NOME, CPF, ENDERECO_ID, USUARIO_ID, STATUS) VALUES ('Allan Lopreti', '12345678912', 1, 1, 'ATIVO');
INSERT INTO ALUNO (NOME, CPF, ENDERECO_ID, USUARIO_ID, STATUS) VALUES ('Allan Felintro', '12345678913', 1, 2, 'ATIVO');
INSERT INTO ALUNO (NOME, CPF, ENDERECO_ID, USUARIO_ID, STATUS) VALUES ('Caio Paiva', '12345678914', 1, 3, 'ATIVO');
INSERT INTO ALUNO (NOME, CPF, ENDERECO_ID, USUARIO_ID, STATUS) VALUES ('Marcos Nofre', '12345678915', 1, 4, 'ATIVO');
INSERT INTO ALUNO (NOME, CPF, ENDERECO_ID, USUARIO_ID, STATUS) VALUES ('Rafael Dorta', '12345678916', 1, 5, 'ATIVO');
INSERT INTO ALUNO (NOME, CPF, ENDERECO_ID, USUARIO_ID, STATUS) VALUES ('Wendel Henrique', '12345678917', 1, 6, 'ATIVO');

-- Inserindo 3 professores
INSERT INTO PROFESSOR (CPF, NOME, ENDERECO_ID, USUARIO_ID, STATUS) VALUES ('12345678918', 'José Souza', 7, 7, 'ATIVO');
INSERT INTO PROFESSOR (CPF, NOME, ENDERECO_ID, USUARIO_ID, STATUS) VALUES ('12345678919', 'Antonio Santos', 8, 8, 'ATIVO');
INSERT INTO PROFESSOR (CPF, NOME, ENDERECO_ID, USUARIO_ID, STATUS) VALUES ('12345678920', 'João Silva', 9, 9, 'ATIVO');

-- Inserindo 3 curso_disciplina
INSERT INTO CURSO_DISCIPLINAS (CURSO_ID, DISCIPLINAS_ID) VALUES (1, 1);
INSERT INTO CURSO_DISCIPLINAS (CURSO_ID, DISCIPLINAS_ID) VALUES (2, 2);
INSERT INTO CURSO_DISCIPLINAS (CURSO_ID, DISCIPLINAS_ID) VALUES (3, 3);

-- Inserindo 3 disciplina_professor
INSERT INTO DISCIPLINA_PROFESSOR (DISCIPLINA_ID, PROFESSOR_ID) VALUES (1, 1);
INSERT INTO DISCIPLINA_PROFESSOR (DISCIPLINA_ID, PROFESSOR_ID) VALUES (2, 2);
INSERT INTO DISCIPLINA_PROFESSOR (DISCIPLINA_ID, PROFESSOR_ID) VALUES (3, 3);


-- Inserindo 3 turmas
INSERT INTO TURMA (NOME) VALUES ('TURMA A1');
INSERT INTO TURMA (NOME) VALUES ('TURMA B2');
INSERT INTO TURMA (NOME) VALUES ('TURMA C3');

-- Inserindo 3 turma_aluno
INSERT INTO TURMA_ALUNO (TURMA_ID, ALUNO_ID) VALUES (1, 1);
INSERT INTO TURMA_ALUNO (TURMA_ID, ALUNO_ID) VALUES (2, 2);
INSERT INTO TURMA_ALUNO (TURMA_ID, ALUNO_ID) VALUES (3, 3);

-- Inserindo 3 turma_disciplina
INSERT INTO TURMA_DISCIPLINA (TURMA_ID, DISCIPLINA_ID) VALUES (1, 1);
INSERT INTO TURMA_DISCIPLINA (TURMA_ID, DISCIPLINA_ID) VALUES (2, 2);
INSERT INTO TURMA_DISCIPLINA (TURMA_ID, DISCIPLINA_ID) VALUES (3, 3);

-- Inserindo 3 turma_aluno
INSERT INTO TURMA_PROFESSOR (TURMA_ID, PROFESSOR_ID) VALUES (1, 1);
INSERT INTO TURMA_PROFESSOR (TURMA_ID, PROFESSOR_ID) VALUES (2, 2);
INSERT INTO TURMA_PROFESSOR (TURMA_ID, PROFESSOR_ID) VALUES (3, 3);