-- Inserindo 6 alunos
INSERT INTO ALUNOS (NOME, CPF, ENDERECO_ID, USUARIO_ID) VALUES ('Allan Lopreti', '12345678912', 1, 1);
INSERT INTO ALUNOS (NOME, CPF, ENDERECO_ID, USUARIO_ID) VALUES ('Allan Felintro', '12345678912', 1, 2);
INSERT INTO ALUNOS (NOME, CPF, ENDERECO_ID, USUARIO_ID) VALUES ('Caio Paiva', '12345678912', 1, 3);
INSERT INTO ALUNOS (NOME, CPF, ENDERECO_ID, USUARIO_ID) VALUES ('Marcos Nofre', '12345678912', 1, 4);
INSERT INTO ALUNOS (NOME, CPF, ENDERECO_ID, USUARIO_ID) VALUES ('Rafael Dorta', '12345678912', 1, 5);
INSERT INTO ALUNOS (NOME, CPF, ENDERECO_ID, USUARIO_ID) VALUES ('Wendel Henrique', '12345678912', 1, 6);

-- Inserindo 3 cursos
INSERT INTO CURSO (NOMECURSO, TURNO) VALUES ('Administracao', 'MANHA');
INSERT INTO CURSO (NOMECURSO, TURNO) VALUES ('Gestao', 'TARDE');
INSERT INTO CURSO (NOMECURSO, TURNO) VALUES ('Tecnologia da Informacao', 'NOITE');

-- Inserindo 3 curso_disciplina
INSERT INTO CURSO_DISCIPLINAS (CURSO_ID, DISCIPLINA_ID) VALUES (1, 1);
INSERT INTO CURSO_DISCIPLINAS (CURSO_ID, DISCIPLINA_ID) VALUES (2, 2);
INSERT INTO CURSO_DISCIPLINAS (CURSO_ID, DISCIPLINA_ID) VALUES (3, 3);

-- Inserindo 3 disciplinas
INSERT INTO DISCIPLINA (NOME) VALUES ('Contabilidade');
INSERT INTO DISCIPLINA (NOME) VALUES ('Lideranca');
INSERT INTO DISCIPLINA (NOME) VALUES ('Estrutura de Dados');

-- Inserindo 3 disciplina_professor
INSERT INTO DISCIPLINA_PROFESSOR (DISCIPLINA_ID, PROFESSOR_ID) VALUES (1, 1);
INSERT INTO DISCIPLINA_PROFESSOR (DISCIPLINA_ID, PROFESSOR_ID) VALUES (2, 2);
INSERT INTO DISCIPLINA_PROFESSOR (DISCIPLINA_ID, PROFESSOR_ID) VALUES (3, 3);

-- Inserindo 6 enderecos
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP) VALUES ('Rua Teste 1', '01', 'São Paulo', 'Bairro Teste 1', '12345678');
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP) VALUES ('Rua Teste 2', '02', 'Pindamonhangaba', 'Bairro Teste 2', '12345678');
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP) VALUES ('Rua Teste 3', '03', 'Campinas', 'Bairro Teste 3', '12345678');
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP) VALUES ('Rua Teste 4', '04', 'Rio Claro', 'Bairro Teste 4', '12345678');
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP) VALUES ('Rua Teste 5', '05', 'Gramado', 'Bairro Teste 5', '12345678');
INSERT INTO ENDERECO (RUA, NUM, CIDADE, BAIRRO, CEP) VALUES ('Rua Teste 6', '06', 'Jundíai', 'Bairro Teste 6', '12345678');

-- Inserindo 3 professores
INSERT INTO PROFESSOR (EMAIL, PASSWORD) VALUES ('professor1@email.com', '123456');
INSERT INTO PROFESSOR (EMAIL, PASSWORD) VALUES ('professor2@email.com', '123456');
INSERT INTO PROFESSOR (EMAIL, PASSWORD) VALUES ('professor3@email.com', '123456');

-- Inserindo 3 turmas
INSERT INTO TURMA (NOME) VALUES ('TURMA A1');
INSERT INTO TURMA (NOME) VALUES ('TURMA B2');
INSERT INTO TURMA (NOME) VALUES ('TURMA C3');

-- Inserindo 3 turma_aluno
INSERT INTO TURMA_ALUNO (TURMA_ID, ALUNO_ID) VALUES (1, 1);
INSERT INTO TURMA_ALUNO (TURMA_ID, ALUNO_ID) VALUES (2, 2);
INSERT INTO TURMA_ALUNO (TURMA_ID, ALUNO_ID) VALUES (3, 3);

-- Inserindo 3 turma_disciplina
INSERT INTO TURMA_DISCIPLINA (TURMA_ID, DISCIPLINA_ID) VALUES (1, 1);
INSERT INTO TURMA_DISCIPLINA (TURMA_ID, DISCIPLINA_ID) VALUES (2, 2);
INSERT INTO TURMA_DISCIPLINA (TURMA_ID, DISCIPLINA_ID) VALUES (3, 3);

-- Inserindo 3 turma_aluno
INSERT INTO TURMA_PROFESSOR (TURMA_ID, PROFESSOR_ID) VALUES (1, 1);
INSERT INTO TURMA_PROFESSOR (TURMA_ID, PROFESSOR_ID) VALUES (2, 2);
INSERT INTO TURMA_PROFESSOR (TURMA_ID, PROFESSOR_ID) VALUES (3, 3);

-- Inserindo 6 usuarios
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('lopreti@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('felintro@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('paiva@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('nofre@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('dorta@email.com', '123456');
INSERT INTO USUARIO (EMAIL, PASSWORD) VALUES ('henrique@email.com', '123456');